version: '3'

services:

  mongo-primary:
    image: cgimongo
    networks:
      - cginet
    volumes:
      - 'mongodata1:/data/db'
      - 'mongoconfig1:/data/configdb'
    deploy:
      placement:
        constraints: [node.labels.cgi.replica == 1]
    depends_on:
      - mongo-secondary1
      - mongo-secondary2
    environ-ment:
      - REPSET_NAME=cgi-mongo-rep
      - MONGO_ROOT=DGc3EjoiOfDl6WofAOBvjPw6wQoOZh9S0AXRo0lQgbwVKD8rn5
      - MONGO_CLUSTER_USER=3Rd56oRooQw31ips97ASDpo77Gskd5weqSD39713sfjhFF
      - MONGO_USER=863cb08a86e8e23721f89aaa63e52ce363391d9a089090884d

  mongo-secondary1:
    image: cgimongo
    networks:
      - cginet
    volumes:
      - 'mongodata2:/data/db'
      - 'mongoconfig2:/data/configdb'
    deploy:
      placement:
        constraints: [node.labels.cgi.replica == 2]
    environment:
      - REPSET_NAME=cgi-mongo-rep

  mongo-secondary2:
    image: cgimongo
    networks:
      - cginet
    volumes:
      - 'mongodata3:/data/db'
      - 'mongoconfig3:/data/configdb'
    deploy:
      placement:
        constraints: [node.labels.cgi.replica == 3]
    environment:
      - REPSET_NAME=cgi-mongo-rep

networks:
  cginet:
    external: true

volumes:
  mongodata1:
    driver: local
  mongodata2:
    driver: local
  mongodata3:
    driver: local
  mongoconfig1:
    driver: local
  mongoconfig2:
    driver: local
  mongoconfig3:
    driver: local